'use strict';

const courses = [
  { slug: 'full-stack-web-development', title: 'Full Stack Web Development', category: 'Full Stack', level: 'Advanced', duration: '12 weeks', price: '₹3,999', instructor: 'Sahil Kapoor', instructorRole: 'Senior Engineer at Google', description: 'Build and deploy modern web applications from the database to the browser.', outcomes: ['Create responsive interfaces with HTML, CSS and React', 'Build REST APIs with Node.js and Express', 'Design MongoDB databases and secure authentication', 'Deploy a complete portfolio project'], modules: ['Web foundations and Git', 'React and state management', 'Node.js APIs and databases', 'Testing, deployment and capstone'], requirements: ['A laptop and internet connection', 'Basic HTML and JavaScript knowledge', '6–8 hours each week'] },
  { slug: 'backend-engineering-nodejs', title: 'Backend Engineering with Node.js', category: 'Backend', level: 'Intermediate', duration: '10 weeks', price: '₹3,499', instructor: 'Anjali Mehta', instructorRole: 'Senior Engineer at Microsoft', description: 'Learn to design reliable, secure and scalable backend services.', outcomes: ['Design production-ready APIs', 'Work with SQL and MongoDB', 'Implement authentication and authorization', 'Use queues, caching and tests'], modules: ['Node.js essentials', 'API design', 'Databases and ORM', 'Security and deployment'], requirements: ['Comfort with JavaScript', 'Basic command-line knowledge', '6 hours per week'] },
  { slug: 'react-nextjs-masterclass', title: 'React & Next.js Masterclass', category: 'Frontend', level: 'Advanced', duration: '8 weeks', price: '₹4,999', instructor: 'Rahul Joshi', instructorRole: 'Senior Engineer at Vercel', description: 'Ship fast, accessible React applications using the modern Next.js stack.', outcomes: ['Build reusable React components', 'Use Next.js routing and server rendering', 'Improve performance and accessibility', 'Publish a polished portfolio site'], modules: ['React patterns', 'Next.js application router', 'Data fetching', 'Performance and launch'], requirements: ['Solid JavaScript fundamentals', 'Some React experience', '6 hours per week'] },
  { slug: 'data-science-machine-learning', title: 'Data Science & Machine Learning', category: 'Data Science', level: 'Intermediate', duration: '14 weeks', price: '₹5,499', instructor: 'Priya Nair', instructorRole: 'Data Scientist at Amazon', description: 'Turn raw data into useful insights and practical machine-learning models.', outcomes: ['Clean and analyse data with Python', 'Visualise results clearly', 'Train and evaluate ML models', 'Present an end-to-end data project'], modules: ['Python for analysis', 'Statistics and visualisation', 'Machine learning', 'Capstone project'], requirements: ['Basic Python recommended', 'High-school mathematics', '7–8 hours per week'] },
  { slug: 'ui-ux-design-fundamentals', title: 'UI/UX Design Fundamentals', category: 'Design', level: 'Beginner', duration: '6 weeks', price: '₹2,999', instructor: 'Aisha Khan', instructorRole: 'Design Lead at Adobe', description: 'Learn a human-centred design process and create interfaces people enjoy using.', outcomes: ['Run user research', 'Create wireframes and prototypes', 'Build a consistent UI system', 'Document a case study'], modules: ['UX process', 'Wireframing', 'Visual design', 'Prototype and portfolio'], requirements: ['No design background needed', 'A laptop with Figma access', '5 hours per week'] },
  { slug: 'python-django-backend', title: 'Python & Django Backend', category: 'Backend', level: 'Intermediate', duration: '10 weeks', price: '₹2,999', instructor: 'Vikram Singh', instructorRole: 'Engineer at Infosys', description: 'Develop secure web applications and REST APIs with Python and Django.', outcomes: ['Build Django applications', 'Create REST APIs with DRF', 'Use relational databases', 'Deploy a secure web service'], modules: ['Python refresh', 'Django models and views', 'REST APIs', 'Testing and deployment'], requirements: ['Basic Python knowledge', 'A laptop and internet', '6 hours per week'] }
];

const internships = [
  { slug: 'frontend-engineering-intern', title: 'Frontend Engineering Intern', company: 'Google', duration: '6 months', stipend: '₹25,000/month', location: 'Remote / Bengaluru', deadline: 'Applications reviewed weekly', skills: ['React', 'TypeScript', 'CSS'], description: 'Work with a mentor to build accessible product experiences for a real product team.', responsibilities: ['Build responsive interface components', 'Participate in code reviews', 'Write maintainable tests', 'Present your final project'], eligibility: ['Students or recent graduates', 'Portfolio or GitHub profile', 'Comfort with React basics'], benefits: ['Completion certificate', 'Weekly mentor sessions', 'Career and resume review'] },
  { slug: 'full-stack-developer-intern', title: 'Full Stack Developer Intern', company: 'Microsoft', duration: '6 months', stipend: '₹30,000/month', location: 'Hybrid / Hyderabad', deadline: 'Applications reviewed weekly', skills: ['Node.js', 'React', 'Azure'], description: 'Contribute to a full-stack product and learn delivery practices from experienced engineers.', responsibilities: ['Develop API and UI features', 'Work with cloud services', 'Collaborate in agile sprints', 'Document engineering decisions'], eligibility: ['Students or recent graduates', 'Knowledge of JavaScript', 'One project you can discuss'], benefits: ['Certificate and PPO consideration', 'Technical mentorship', 'Mock interview support'] },
  { slug: 'data-science-intern', title: 'Data Science Intern', company: 'Amazon', duration: '3 months', stipend: '₹20,000/month', location: 'Remote', deadline: 'Applications reviewed weekly', skills: ['Python', 'Machine Learning', 'SQL'], description: 'Explore data sets, build simple models and communicate actionable recommendations.', responsibilities: ['Prepare and analyse data', 'Build baseline models', 'Create reports and dashboards', 'Share findings with stakeholders'], eligibility: ['Students or recent graduates', 'Python and statistics basics', 'Interest in data problems'], benefits: ['Completion certificate', 'Project feedback', 'Career guidance'] }
];

module.exports = { courses, internships };
